### ISSUE TITLE
Publish release libraries for linux arm64

### ISSUE THREAD

**Issue by rpobulic** [hyperledger/indy-vdr#101]
Wheels are published for macos universal and linux x86-64, but not for linux arm64. Could the build be updated to publish releases for this architecture?

**Comment by TimoGlastra** [comment]
I'm going to work on this task, as it's also needed for the JavaScript wrapper

@rpobulic are you interested in the a release with linux ARM support for the Python package?

**Comment by rpobulic** [comment]
Yes please

**Comment by blu3beri** [comment]
Should be resolved in: https://github.com/hyperledger/indy-vdr/pull/119
