### ISSUE TITLE
Unable to run indy vdr 

### ISSUE THREAD

**Issue by abhimin** [hyperledger/indy-vdr#108]
I have installed indy vdr through pip install and when I use indy-vdr-proxy --host 0.0.0. --port 7564 --genesis url given.
But getting indy vdr proxy command not found

**Comment by blu3beri** [comment]
Hi,

You would need to install the `indy-vdr-proxy` through Rust as pip just installs the library, I think.

You can install the proxy with the following commands:

```sh
git clone https://github.com/hyperledger/indy-vdr
cd indy-vdr/indy-vdr-proxy
cargo install --path .
```

cargo can be installed here: https://rustup.rs

**Comment by abhimin** [comment]
Thank you for your prompt reply...
Is there any way I can use indy vdr docker image and Integrate with tailsserver

**Comment by blu3beri** [comment]
I am not too sure about that. I will close this issue, you can open it again if you have additional issues with running `indy-vdr-proxy`.
