### ISSUE TITLE
Is indy vdr mandatory 

### ISSUE THREAD

**Issue by abhimin** [hyperledger/indy-vdr#109]
I clone the tails server code and trying to build the tails server docker file and it successfully build but when I run tails image getting indy-vdr-proxy url is mandatory.

Is indy-vdr-proxy url mandatory or can I give von network url here for indy proxy url.

**Comment by WadeBarnes** [comment]
Closing.  This is an issue related to [bcgov/indy-tails-server](https://github.com/bcgov/indy-tails-server).  Related issue is here; https://github.com/bcgov/indy-tails-server/issues/43
