### ISSUE TITLE
Release Indy VDR for React Native to NPM

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/indy-vdr#115]
Continuation of https://github.com/hyperledger/indy-vdr/issues/113, but focuses on the React Native implementation

The iOS & Android build is currently broken and needs some extra work.

TODO
- [ ] ~~add iOS build~~ -> moved to separate task (https://github.com/hyperledger/indy-vdr/issues/122)
- [x] add Android build
- [ ] Fix react native setup (check if it works with node-pre-gyp paths)
- [ ] Add example app for react native

**Comment by blu3beri** [comment]
Partially resolved point 1 with: #118 
iOS is blocking now as there might be an issue, at least for my setup, with cmake-rs (related issue: https://github.com/rust-lang/cmake-rs/issues/173)
