### ISSUE TITLE
Non-deterministic issue with the javascript wrapper in Node.js

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/indy-vdr#191]
CI keeps failing on this step: https://github.com/hyperledger/indy-vdr/actions/runs/5082667192/jobs/9145294433

With the error:

```
FAIL tests/GetAttribRequest.test.ts (21.485 s)
  ● GetAttribRequest › Submit request

    Pool timeout: Request was interrupted

      114 |     const indyVdrErrorObject = JSON.parse(nativeError.deref() as string) as IndyVdrErrorObject
      115 |
    > 116 |     throw new IndyVdrError(indyVdrErrorObject)
          |           ^
      117 |   }
      118 |
      119 |   public get nativeIndyVdr() {

      at NodeJSIndyVdr.handleError (src/NodeJSIndyVdr.ts:116:11)
      at cb (src/NodeJSIndyVdr.ts:87:16)
      at Object.<anonymous> (../node_modules/ffi-napi/lib/callback.js:66:27)
```

It happens for some functions and the amount of times it happens is different each run.

It passes here: https://github.com/hyperledger/indy-vdr/actions/runs/5044489119/jobs/9048660679

The errors seem to be thrown from the native library, with version: `v0.4.0-dev.15`.

**Comment by blu3beri** [comment]
https://github.com/hyperledger/indy-vdr/pull/184 Seems to be the first PR where this is noticed. No changes have been made to indy-vdr for a couple of months.

**Comment by TimoGlastra** [comment]
We're using a live network for tests still I think. Maybe we should switch to a local network that is set-up in CI?

**Comment by TimoGlastra** [comment]
Here's the CI that set's it up: https://github.com/hyperledger/indy-vdr/blob/main/.github/workflows/build.yml#LL84C1-L88C97

we just have to configure our tests to use the local pool
