### ISSUE TITLE
Refactor request builder

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/indy-vdr#199]
Nothing urgent, but creating this to track a potential improvement, mainly when consuming `indy-vdr` from another Rust project.

Function `build_nym_request` takes argument `role: Option<String>` which can have variety of values to represent a role - for example if you want to express "endorser", you can pass in any of following strings: `"TRUST_ANCHOR", "ENDORSER", "101"`. 

Ideally there would be defined user facing enum, something like 
```
pub enum IndyRole {
    Steward,
    Trustee,
    Endorser,
    NetworkMonitor,
}
```

To maintain backwards compatibility for FFI, values `"TRUST_ANCHOR", "ENDORSER", "101"` should be converted to appropriate enum variant on the FFI layer. (some kind of unification conversion currently happens inside of `build_nym_request`)

There might be more instances of the same pattern, but this is a particular one I've run into.

**Comment by andrewwhitehead** [comment]
Agreed, this is probably something we can sneak into the next minor release.
