### ISSUE TITLE
Usage of lerna 7 in CI breaks publishing script

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/indy-vdr#217]
```
lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces 
```

Should probably update to use lerna v7, but then also pin to use v7 to not break again in the future

**Comment by andrewwhitehead** [comment]
I think this is resolved now, I suppose we just run the workflow again to publish the packages?
