### ISSUE TITLE
Create a Tails Server capability based on indy-vdr-proxy

### ISSUE THREAD

**Issue by swcurran** [hyperledger/indy-vdr#24]
With Indy anoncreds 1 revocation now supported in (at least) ACA-Py, we need places for issuers to publish tails files and from which holders can download them. As such, we'd like to create such a service around indy-vdr.  BC Gov is planning to host an instance of a tails server that others could use.

Here is a rough outline of the proposed design:

- The service would have two sets of endpoints, one for posting a tails file, the other for downloading one.
- The posting service would expect from the issuer:
  - A call (or two?) with:
     - a mechanism to find the ledger (genesis file or URL)
     - the ID of the revocation registry for the tails file
     - the tails file, perhaps as a URL or passed as a follow up call.
     - perhaps a signature from the issuer based on it's DID on the ledger
  - The tails server would validate the existence of the ledger, revo registry and any other data
  - If all good, get the tails file and make it available at a known location constructed (somehow - TBD) from the ledger and revocation registry.
- The download service would simply make the file available for download a tails file when asked.

We would want a least a docker-compose file for the service so that it can be easily deployed and testing.  BC Gov would likely deploy the service on OpenShift.

Glad to help with any questions for getting started on this.

**Comment by nrempel** [comment]
I'll take this on

**Comment by andrewwhitehead** [comment]
https://github.com/bcgov/indy-tails-server
