### ISSUE TITLE
Instalation doesn't work on Macs

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/indy-vdr#260]
When installing this package via npm in a third-party project (Hyperledger Cacti), one obtains:

`➤ YN0007: │ @hyperledger/indy-vdr-nodejs@npm:0.2.0-dev.3 must be built because it never has been before or the last one failed
➤ YN0009: │ @hyperledger/indy-vdr-nodejs@npm:0.2.0-dev.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/05/_tsk4bn52_52y3vpwhhmmwk80000gn/T/xfs-2c17d0ad/build.log)
➤ YN0009: │ @hyperledger/indy-vdr-nodejs@npm:0.2.0-dev.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/05/_tsk4bn52_52y3vpwhhmmwk80000gn/T/xfs-1368b8ed/build.log)
➤ YN0009: │ @hyperledger/indy-vdr-nodejs@npm:0.2.0-dev.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/05/_tsk4bn52_52y3vpwhhmmwk80000gn/T/xfs-23703039/build.log)``

The logs say:
`node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@21.5.0 | darwin | arm64
(node:61506) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-pre-gyp info check checked for "/Users/rafaelapb/Projects/blockchain-integration-framework/packages/cactus-plugin-ledger-connector-aries/node_modules/@hyperledger/indy-vdr-nodejs/native/indy_vdr.node" (not found)
node-pre-gyp http GET https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0/library-darwin-aarch64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0/library-darwin-aarch64.tar.gz 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0/library-darwin-aarch64.tar.gz
node-pre-gyp ERR! stack     at /Users/rafaelapb/Projects/blockchain-integration-framework/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node-pre-gyp ERR! System Darwin 23.3.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/21.5.0/bin/node" "/Users/rafaelapb/Projects/blockchain-integration-framework/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--target_arch=aarch64" "--target_platform=darwin"
node-pre-gyp ERR! cwd /Users/rafaelapb/Projects/blockchain-integration-framework/packages/cactus-plugin-ledger-connector-aries/node_modules/@hyperledger/indy-vdr-nodejs
node-pre-gyp ERR! node -v v21.5.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
node:child_process:965`

Implying that node-gyp tries to fetch `https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0/library-darwin-aarch64.tar.gz` instead of `https://github.com/hyperledger/indy-vdr/releases/download/v0.4.1/library-darwin-universal.tar.gz` (which i believe would be the canonical package for macos).

OS info:
sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60
sw_vers -productVersion
14.3.1
uname -m
arm64

tested with node version: 18.18.2 and 21.5.0

To reproduce (on a mac):
1. git clone https://github.com/hyperledger/cacti
2. yarn install

Any advice on how to proceed?

**Comment by TimoGlastra** [comment]
Can you try it with stable 0.2.0 release of indy-vdr JS wrapper?

There was an issue in older dev releases with universal vs arch specific builds for macOS

**Comment by RafaelAPB** [comment]
> Can you try it with stable 0.2.0 release of indy-vdr JS wrapper?
> 
> There was an issue in older dev releases with universal vs arch specific builds for macOS

It does fix the issue. Thanks for the quick answer!
