### ISSUE TITLE
Indy-shared crate?

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/indy-vdr#35]
In my current refactoring PR I've added a vdr-shared crate containing some utilities and traits that are used by both the library and the integration tests, because the integration tests can only use public exports from the indy-vdr crate. Currently this includes the following:

- base58 encode/decode
- sha2 hashing (via Ursa)
- ed25519 verkey derivation (via Ursa)
- Qualifiable and Validatable traits, and ValidationError
- test code to create genesis transactions

I think it makes sense to expand this with the Indy identifier and ledger data types (SchemaId, CredentialDefinitionId, .. Schema, CredentialDefinition ..) as those are also used in credx, and would be used in the storage backend as well. The DID and Verkey handling code would probably go there as well, and maybe MerkleTree. Then this might be published as a separate crate (and maybe Hyperledger project) to be used as a dependency. I believe the SDK has a similar setup internally.

Are there any practical or technical reasons not to do this?

@Artemkaaas @jovfer @esplinr @swcurran

**Comment by jovfer** [comment]
@andrewwhitehead we definitely need some shared crates to be used across VDR, CredX, some integration tests. Could you please take a look on `indy-api-types` and `indy-utils` crates in IndySDK and compare with your list?

**Comment by jovfer** [comment]
@dhh1128 @KitHat FYI

**Comment by andrewwhitehead** [comment]
It looks like `indy-api-types` is not relevant, apart from having a version of the Validatable trait.
`indy-utils` has the WQL support, which could belong in a shared crate, as well as a bunch of crypto support code which is not needed so far. If the shared crate includes pack and unpack then some of that could be updated to use Ursa.

**Comment by andrewwhitehead** [comment]
Added a first crack at the separated crates here: https://github.com/andrewwhitehead/indy-shared-rs

**Comment by swcurran** [comment]
Hey @jovfer - could you take a look at the repo that Andrew created?  If it is what we need, we'd like to push it into BCGov -> Hyperledger pretty quickly and get it into the CI/CD system.

Not sure if you have time these days for that, but it would be help if you could take a quick look.

Thanks!

**Comment by andrewwhitehead** [comment]
I've just transferred it to bcgov, but I'm still working on some additions (pack/unpack).
