### ISSUE TITLE
Will this library be following the contract for resolution defined in DID Core?

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/indy-vdr#37]
As of recently, a contract has been being discussed in the DID Core specification with some of the normative PRs still to come. The non normative structure has been merged in and issues [#263](https://github.com/w3c/did-core/pull/263), [#264](https://github.com/w3c/did-core/pull/264), and [#265](https://github.com/w3c/did-core/pull/265) will be bringing in the normative statements. Is the intent of this library to move in the direction eventually, and if so what sorts of input would you have for those PRs to align with this implementation?

**Comment by andrewwhitehead** [comment]
This library provides a native interface to a specific Indy ledger. I believe a conformant DID resolver could be built around it, but I don't see anything that needs updating at the moment.

**Comment by kdenhartog** [comment]
Ahh gotcha, so this would be like a driver and the resolver/ dereferencer library would wrap around this. Thanks for the additional clarity.
