### ISSUE TITLE
Could support genesis transactions at URL

### ISSUE THREAD

**Issue by sklump** [hyperledger/indy-vdr#4]
https://github.com/andrewwhitehead/indy-vdr/blob/414b1903c2a9efb99ee2a9e6c844394f822ca094/indy-vdr-proxy/src/main.rs#L52

Could support URL here?

Any issues I put up here are tiny in the face of how awesome this software is as a whole.

**Comment by andrewwhitehead** [comment]
It would be easier to support there in the proxy because it already has an HTTP client library. I didn't really want to add that as a dependency on the main rust library. Also thanks!
