### ISSUE TITLE
Retrieve real IP address instead of binding address of 0.0.0.0

### ISSUE THREAD

**Issue by lohanspies** [hyperledger/indy-vdr#43]
The [indy-node-monitor](https://github.com/hyperledger/indy-node-monitor) repo make use of indy-vdr to collect metrics from the ledgers to enable monitoring and visualisation of the health of indy networks. One of the attributes being collected is the node_ip and client_ip of nodes. Some nodes bind to the 0.0.0.0 IP address for these services. The current indy-vdr implementation retrieves the bind IP address, however from a metrics perspective we are looking for the real IP address of the node and not the bind IP address of the node.

Would it be possible to retrieve real node IP addresses for the node and client service respectively?

**Comment by swcurran** [comment]
@andrewwhitehead -- can you look and assess this?  Thanks.

**Comment by WadeBarnes** [comment]
For monitoring purposes it would be good to have the `internal` and `public` IP/Port configurations reported.

The results of `get-validator-info` return the `internal` IP/Port configurations of the node (the local settings of the given node), not the `public` IP/Port configurations.  When a node is registered on the ledger (using the `ledger node` command) the `public` IP/Ports are used.

I don't think the node is self aware of it's public addresses, so additional calls may be required in the background to collect this information.

**Comment by WadeBarnes** [comment]
@andrewwhitehead pointed at a possible solution that I'm going to investigate.

**Comment by WadeBarnes** [comment]
From the python wrapper `pool.get_transactions()` (which calls into the associated rust method) can be used to get all of the pool transactions for the ledger.  These transactions will contain the IP address and service state of a node, however IP addresses and services can be changed independently in transactions so there isn't a single one that provides the "current" state of a given node.

**Comment by swcurran** [comment]
@andrewwhitehead -- can you do this?  Is this the right way to do this, or should we do this a different way?  For example, is there a call to get a complete set of genesis file transactions that lists all of the current nodes?  That would have all of the IP addresses we need.

On the other hand, it would be worth seeing if this is just a mistake and it was intended that the data in the validator info would be the external IP addresses.  It certainly makes more sense that be the case.

**Comment by WadeBarnes** [comment]
> On the other hand, it would be worth seeing if this is just a mistake and it was intended that the data in the validator info would be the external IP addresses. It certainly makes more sense that be the case.

This is not a mistake.  The nodes only know about the IP addresses they listen on locally.  They are unaware (by design) of any proxy layers between themselves and the public internet.
