### ISSUE TITLE
partial rewrite of the nodejs wrapper

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/indy-vdr#76]
Right now I am working on the react native wrapper for indy-vdr. I noticed that there is a wrapper for nodejs, but it seems a bit outdated, I could be wrong here. In order to have a consistent api with the react native side, as these wrappers both will be used by AFJ this is rather essential, we must do a partial rewrite of this wrapper. 

@Patrik-Stas Do you have any concerns with this, as you are the main author of the wrapper?

The only changes that will probably be made, still have to do a deeper dive into this, are a consistent api and make use of the shared interfaces between the upcoming react native wrapper and nodejs.

I will also make sure that both packages will be properly released on npm.

**Comment by TimoGlastra** [comment]
I'm going to close this. The wrappers now live under different folders. We may want to remove the nodejs directory at some point as we have a more up to date replacement
